### ISSUE TITLE
provider helm produced invalid new value for .version

### ISSUE THREAD

**Issue by skuldy** [astronomer/terraform-kubernetes-astronomer#10]
module.astronomer.null_resource.helm_repo: Creating...
module.astronomer.null_resource.helm_repo: Provisioning with 'local-exec'...
module.astronomer.kubernetes_secret.astronomer_tls: Creating...
module.astronomer.null_resource.helm_repo (local-exec): Executing: ["/bin/sh" "-c" "    if [ ! -d ./helm.astronomer.io ]; then\n      git clone https://github.com/astronomer/helm.astronomer.io.git\n    fi\n    cd \"./helm.astronomer.io\" && \\\n    git checkout v0.9.1-alpha.4\n"]
module.astronomer.null_resource.helm_repo (local-exec): Note: checking out 'v0.9.1-alpha.4'.

module.astronomer.null_resource.helm_repo (local-exec): You are in 'detached HEAD' state. You can look around, make experimental
module.astronomer.null_resource.helm_repo (local-exec): changes and commit them, and you can discard any commits you make in this
module.astronomer.null_resource.helm_repo (local-exec): state without impacting any branches by performing another checkout.

module.astronomer.null_resource.helm_repo (local-exec): If you want to create a new branch to retain commits you create, you may
module.astronomer.null_resource.helm_repo (local-exec): do so (now or later) by using -b with the checkout command again. Example:

module.astronomer.null_resource.helm_repo (local-exec):   git checkout -b <new-branch-name>

module.astronomer.null_resource.helm_repo (local-exec): HEAD is now at 005bf00... Bump to 0.9.1-alpha.4
module.astronomer.null_resource.helm_repo: Creation complete after 1s [id=8093483647969451662]
module.astronomer.kubernetes_secret.astronomer_tls: Creation complete after 1s [id=astronomer/astronomer-tls]
module.astronomer.kubernetes_secret.astronomer_bootstrap: Creating...
module.astronomer.kubernetes_secret.astronomer_bootstrap: Creation complete after 0s [id=astronomer/astronomer-bootstrap]

Error: Provider produced inconsistent final plan

When expanding the plan for module.astronomer.helm_release.astronomer_local to
include new values learned so far during apply, provider "helm" produced an
invalid new value for .version: was cty.StringVal("0.10.0-alpha.1"), but now
cty.StringVal("0.9.1-alpha.4").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by sjmiller609** [comment]
This bug is solved in the new top-level terraform module https://github.com/astronomer/terraform-aws-astronomer-enterprise
