### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/terraform-kubernetes-astronomer#5]
1 and 2 can run simultaneously

1)
- terraform apply on an existing CI cluster(s) (maybe just AWS at first, then both AWS and GCP after we have CI environments set up for terraform-aws-astronomer-aws and terraform-google-astronomer-gcp)
- terraform destroy

2)
- terraform apply the previous, working version (most recent terraform registry tag)
- start a few, simple, external / black-box health checks (like checking a few prometheus endpoints) running in the background. Don't go overboard on the health checks at first, we can expand the test coverage as we go. Alternatively, if Prometheus already does this, then just check promethus at the end and check that promethus doesn't have any monitoring gaps. Whichever option is easier at first.
- Do an update to this version, confirm there were ~~no failed health checks~~ an acceptable level of failures

We will continuously be maturing and expanding this testing. For completion of this issue, we just want an outline of apply, destroy, and upgrade testing. Eventually, we may have multiple deploying at the same time on the same cluster in order to test various configurations and / or multiple simultaneous contributions by different developers.

**Comment by sjmiller609** [comment]
@kaxil I'm interested to hear if you have opinions on this one.

**Comment by sjmiller609** [comment]
I have been a fan of using python's 'behave' module for increasing readability of the above kind of tests. That way it could look something like this (rough idea):

Given an existing cluster on AWS
Then terraform apply
And terraform destroy

Given an existing cluster on AWS
And the previous version is applied
When black-box monitoring turned enabled
Then terraform apply
And black-box monitoring did not fail
And terraform destroy

**Comment by kaxil** [comment]
Just one question - why not destroying everything first -> terraform apply -> terraform destory ?

Is one of the reason to check whether we can update from the last version to the latest master?

**Comment by sjmiller609** [comment]
I'm worried about customers or us updating and causing downtime. There have been known interrupts when doing a helm upgrade, especially surrounding pgbouncer component. @schnie any thoughts? @kaxil I will separate the above into separate tests so one of them is as you are saying

**Comment by sjmiller609** [comment]
Also - instead of 'no downtime' required, we should just measure downtime and have an acceptable limit.

**Comment by kaxil** [comment]
Makes sense, in that case, we should test both 1) Clean Install; 2) Upgrade.

I haven't used python `behave` but just schemed over it and looks good.

**Comment by sjmiller609** [comment]
yeah I like it. it's just a nice way to put sentences in front of any python function

**Comment by schnie** [comment]
If we `helm upgrade` the platform and we're specifying a full version bump of the platform (not just a config change), every platform pod will get updated to the new version. Ideally this is very minimal, if any actual downtime to the users. Orbit and Houston will do a rolling restart so there should be very little disruption from an external perspective. 

Upgrading the platform does not touch the individual airflow helm releases. These are completely independent from the platform, so upgrading the platform will not disrupt the pgbouncers.

Once the platform is upgraded, users will see that there is a new version of the Airflow chart available and see a button to upgrade their deployment. When they click that button, it makes an API request to Houston to `helm upgrade` the airflow. At this point all those airflow deployment pods get rebooted and upgraded, including pgbouncer.

**Comment by sjmiller609** [comment]
I have added an MVP for CI pipeline. we can create additional issues to complete this story
